[tool.poetry]
name = "template-py-rest-microservice"
version = "1.0.0"
description = "This repository acts like a project template for all Python based microservice built using FastAPI."
authors = ["Ashwin Hegde <ashwin.hegde3@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
uvicorn = "^0.18.2"
fastapi = "^0.79.0"
fastapi-versioning = "^0.10.0"
fastapi-limiter = "^0.1.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
